[package]
name = "nekoos"
version = "0.1.0"
authors = ["Yuki Kitajima <admin@endcat.cn>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"